<a href="https://colab.research.google.com/github/Srikanth-15L/DoctorManagament/blob/main/Dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.initializers import Ones

In [27]:
model=Sequential([Dense(4,activation="tanh",input_shape=(3,),bias_initializer=Ones()),
                        Dense(2,activation="tanh",bias_initializer=Ones()),
                        Dense(1,activation="sigmoid",bias_initializer=Ones)])


In [28]:
model.compile(optimizer="Adam",loss="binary_crossentropy",metrics=['accuracy'])

In [29]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_13 (Dense)                │ (None, 4)              │            16 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29 (116.00 B)

 Trainable params: 29 (116.00 B)

 Non-trainable params: 0 (0.00 B)

In [30]:
import numpy as np
vec=np.arange(1,25)
print(vec)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [33]:
import tensorflow as tf
ran=tf.convert_to_tensor(vec)
s=tf.reshape(ran,(2,3,4))
s




<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [35]:
import tensorflow as tf

# Convert the numpy vector into a rank 3 tensor
tensor_rank_3 = tf.convert_to_tensor(vec, dtype=tf.int32)
tensor_rank_3 = tf.reshape(tensor_rank_3, (2, 3, 4))  # Reshaping it to a 3D tensor with shape (2, 3, 4)
print("Rank 3 Tensor:\n", tensor_rank_3)


Rank 3 Tensor:
 tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int32)


In [42]:
s=tf.convert_to_tensor(vec)
print(tf.reshape(s,(2,3,4)))
print(tf.__version__)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int64)
2.18.0


In [46]:
phy=tf.config.list_physical_devices()
print(phy)
gpu_available=tf.config.list_physical_devices("Gpu")
if gpu_available:
  print("gpu available")
else:
  print("not available")


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
not available


In [47]:
# Get the type and number of physical devices available
physical_devices = tf.config.list_physical_devices()
print("Physical Devices:", physical_devices)

# Test whether GPU is available
gpu_available = tf.config.list_physical_devices('GPU')
if gpu_available:
    print("GPU Available:", gpu_available)
else:
    print("No GPU available.")


Physical Devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
No GPU available.


In [49]:
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [63]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.optimizers import RMSprop

In [64]:
max_fea=10
maxlen=200
imdb.load_data(num_words=max_fea)

((array([list([1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 9, 2, 2, 2, 5, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 6, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 8, 2, 8, 2, 5, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 8, 4, 2, 2, 2, 2, 2, 4, 2, 7, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
         list([1, 2, 2, 2, 2, 2, 2, 5, 6, 2, 2, 2, 2, 2, 4, 2, 8, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 8, 2, 2, 7, 4, 2, 2, 2, 4, 2, 9, 2, 2, 5, 2, 4, 2, 9, 2, 2, 4, 2, 9, 2, 2, 4, 2, 9, 4, 2, 2, 2, 4, 2, 5, 2, 2, 2, 2, 2, 4, 2, 9, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 5, 2, 2, 2, 2, 4, 2, 9, 2, 2, 7, 2, 2, 2, 2, 2, 2,

In [65]:
max_fre=10000
max_len=200
imdb.load_data(new_words=max_fre)

((array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 22665, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 21631, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 19193, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 10311, 8, 4, 107, 117, 5952, 15, 256, 4, 31050, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 12118, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
         list([1, 19

In [66]:
(x_train,y_train),(x_test,y_test)=imdb.load_data(num_words=max_fre,maxlen=max_len)

In [67]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(14244,)
(14244,)
(14669,)
(14669,)


In [71]:
x_train=pad_sequences(x_train)
x_test=pad_sequences(x_test)
x_train.shape
x_test.shape

(14669, 199)

In [ ]:
Sequential([Embedding(input=max_fre,output_dim=128,input_length=maxlen)])